version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "ap-northeast-1"
    DOCKER_USER: AWS
    REPOSITORY_URI: "<ECRのURIをコピーする>"
    IMAGE_NAME: app

phases:
  # pre_build:
  #   commands:
  #     - echo "$DOCKER_PAT" | docker login --username $DOCKER_USER --password-stdin

  build:
    commands:
      - docker buildx build --platform linux/amd64,linux/arm64 .

  post_build:
    commands:
      - echo "ECRへpush"
      # - docker push "$REPOSITORY_URI/$IMAGE_NAME:latest"
