version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "ap-northeast-1"
    DOCKER_USER: AWS
    REPOSITORY_URI: "<ECRのURIをコピーする>"
    IMAGE_NAME: app

phases:
  build:
    commands:
      - echo "コード変更しました3"
      # - docker build -t "$REPOSITORY_URI/$IMAGE_NAME:latest" .
  post_build:
    commands:
      - echo "ECRへpush"
      # - docker push "$REPOSITORY_URI/$IMAGE_NAME:latest"
      # - printf '{"Version":"1.0","ImageURI":"%s"}' $REPOSITORY_URI/$IMAGE_NAME:$IMAGE_TAG > imageDetail.json
artifacts:
  files: imageDetail.json
