version: 0.2

env:
  variables:
    ARCH: amd64
    ECR_REGISTRY: 175142243308.dkr.ecr.us-east-1.amazonaws.com
    ECR_REPOSITORY: tadashi-dbc-demo
    DOCKER_ORG: demotnemoto
  secrets-manager:
    DOCKER_USER: ${SECRETS_NAME}:DOCKER_USER
    DOCKER_PAT: ${SECRETS_NAME}:DOCKER_PAT

phases:
  install:
    commands:
      # buildx のインストール
      - BUILDX_URL=$(curl -s https://raw.githubusercontent.com/docker/actions-toolkit/main/.github/buildx-lab-releases.json | jq -r ".latest.assets[] | select(endswith(\"linux-$ARCH\"))")
      - mkdir -vp ~/.docker/cli-plugins/
      - curl --silent -L --output ~/.docker/cli-plugins/docker-buildx $BUILDX_URL
      - chmod a+x ~/.docker/cli-plugins/docker-buildx

  pre_build:
    commands:
      # AWS ECR へのログイン
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
      # Docker (Build Cloud) へのログイン
      - echo "$DOCKER_PAT" | docker login --username $DOCKER_USER --password-stdin
      # クラウドビルダーの指定
      - docker buildx create --use --driver cloud $DOCKER_ORG/demo

  build:
    commands:
      # イメージタグ
      - IMAGE_TAG=$(echo ${CODEBUILD_RESOLVED_SOURCE_VERSION} | head -c 7)
      # コンテナイメージのビルド・AWS ECR へのプッシュ
      - docker buildx build --platform linux/amd64,linux/arm64 --push --tag "${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}" .
