version: 0.2

env:
  variables:
    ECR_REGISTRY: 175142243308.dkr.ecr.us-east-1.amazonaws.com
    ECR_REPOSITORY: tadashi-dbc-demo

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

  build:
    commands:
      - docker build --push --tag "${ECR_REGISTRY}/${ECR_REPOSITORY}:latest" .
